
const houre =[
    { label: 'Select...', value: ''  },
    { label: '07:00', value: '07:00' },
    { label: '07:30', value: '07:30' },
    { label: '08:00', value: '08:00' },
    { label: '08:30', value: '08:30' },
    { label: '09:00', value: '09:00' },
    { label: '09:30', value: '09:30' },
    { label: '10:00', value: '10:00' },
    { label: '10:30', value: '10:30' },
    { label: '11:00', value: '11:00' },
    { label: '11:30', value: '11:30' },
    { label: '12:00', value: '12:00' },
    { label: '12:00', value: '12:00' },
    { label: '12:30', value: '12:30' },
    { label: '13:00', value: '13:00' },
    { label: '13:30', value: '13:30' },
    { label: '14:00', value: '14:00' },
    { label: '14:30', value: '14:30' },
    { label: '15:00', value: '15:00' },
    { label: '15:30', value: '15:30' },
    { label: '16:00', value: '16:00' },
    { label: '16:30', value: '16:30' },
    { label: '17:00', value: '17:00' },
    { label: '17:30', value: '17:30' },
    { label: '18:00', value: '18:00' },
    { label: '18:30', value: '18:30' },
    { label: '19:00', value: '19:00' },
    { label: '19:30', value: '19:30' },
    { label: '20:00', value: '20:00' },
    { label: '20:30', value: '20:30' },
    { label: '21:00', value: '21:00' },
    { label: '21:30', value: '21:30' },
    { label: '22:00',value: '22:00'  },
  ]



  const City =[
    { label: 'Select...', value: ''  },
    { label: 'אוניברסיטת אריאל' , value: 'אוניברסיטת אריאל'},
    { label: 'תל אביב-יפו',value: 'תל אביב-יפו' },
    { label: 'חולון', value: 'חולון'},
    { label: 'בת ים' ,value: 'בת ים'},
    { label: 'אזור' ,value: 'אזור'},
    { label: 'קרית אונו', value: 'קרית אונו', },
    { label: 'כפר שמריהו',value: 'כפר שמריהו', },
    { label: 'רמת גן', value: 'רמת גן' },
    { label: 'גבעתיים', value: 'גבעתיים' },
    { label: 'בני ברק' , value: 'בני ברק'},
    { label: 'הוד השרון', value: 'הוד השרון',},
    { label: 'הרצליה', value: 'הרצליה'},
    { label: 'כפר סבא',value: 'כפר סבא' },
    { label: 'כפר קאסם',value: 'כפר קאסם' },
    { label: 'פתח תקווה',value: 'פתח תקווה' },
    { label: 'ראש העין', value: 'ראש העין'},
    { label: 'רמת השרון' ,value: 'רמת השרון'},
    { label: 'רעננה', value: 'רעננה' },
    { label: 'גני תקווה',value: 'גני תקווה' },
    { label: 'אלעד',value: 'אלעד' },
    { label: 'גבעת שמואל',value: 'גבעת שמואל' },
    { label: 'סביון',value: 'סביון'},
    { label: 'כוכב יאיר צור יגאל',value: 'כוכב יאיר צור יגאל', },
    { label: 'כפר יונה', value: 'כפר יונה'},
    { label: 'נתניה',value: 'נתניה'  },
    { label: 'אבן יהודה' ,value: 'אבן יהודה'},
    { label: 'אליכין' ,value: 'אליכין'},
    { label: 'זמר',value: 'זמר',  },
    { label: 'פרדסיה',value: 'פרדסיה' },
    { label: 'קדימה צורן',value: 'קדימה צורן'  },
    { label: 'תל מונד',value: 'תל מונד'},
    { label: 'עמק חפר' ,value: 'עמק חפר'},
    { label: 'באר יעקב',value: 'באר יעקב' },
    { label: 'לוד',value: 'לוד' },
    { label: 'רמלה',value: 'רמלה' },
    { label: 'מודיעין-מכבים-רעות', value: 'מודיעין-מכבים-רעות',},
    { label: 'בית דגן',value: 'בית דגן' },
    { label: 'שוהם' ,value: 'שוהם' },
    { label: 'יבנה' ,value: 'יבנה'},
    { label: 'נס ציונה', value: 'נס ציונה'},
    { label: 'ראשון לציון' ,value: 'ראשון לציון',},
    { label: 'רחובות' ,value: 'רחובות'},
    { label: 'בני עי"ש', value: 'בני עי"ש',},
    { label: 'גדרה',value: 'גדרה' },
    { label: 'גן יבנה',value: 'גן יבנה' },
    { label: 'מזכרת בתיה', value: 'מזכרת בתיה'},
    { label: 'קריית עקרון', value: 'קריית עקרון'},
    { label: 'גבעת ברנר', value: 'גבעת ברנר'},
    { label: 'גדרות',value: 'גדרות' },
    { label: 'נחל שורק',value: 'נחל שורק' },
    { label: 'בית שמש',value: 'בית שמש'  },
    { label: 'ירושלים', value: 'ירושלים'},
    { label: 'אבו גוש' ,value: 'אבו גוש'},
    { label: 'מבשרת ציון', value: 'מבשרת ציון'},

  ]


  export {houre, City}
